MASS_LOWER_BOUND = 2
MASS_UPPER_BOUND = 10

ELASTICITY_LOWER_BOUND = 0
ELASTICITY_UPPER_BOUND = 0.8

FRICTION_LOWER_BOUND = 0
FRICTION_UPPER_BOUND = 1

NUM_PROPERTIES = 3

POPULATION_SIZE = 500
NUM_ITERATIONS = 100
NUM_OFFSPRING = 100